### ISSUE TITLE
Obscure eval interpretation

### ISSUE THREAD

**Issue by orzklv** [akumarujon/runner#7] opened 2023-02-02 19:01 UTC
This is possibly the most obscure mistake I've seen in the past 5 years. Like, seriously. Instead of executing a piece of input code directly, run it in a sandbox. https://github.com/ascii-gang/runner/blob/a1e6d1c822fc2fc449fa3ac8fd7a6c8aee964c2b/runner/mod.ts#L8

**Comment by katsuki-yuri** [comment] 2023-02-02 19:02
You may consider creating a sandbox service or server which will run passing code inside a sandbox and returns the output in the end or on live using websocket.

**Comment by katsuki-yuri** [comment] 2023-02-02 19:03
Using this line of code, it's possible to escalate many shitty thingies and even the worst, run the shebang code and execute it on system shell which is what we call "fiasko" for your server.

**Comment by tapnisu** [comment] 2023-02-03 13:57
That's a feature, not a bug :D

**Comment by user6879** [comment] 2023-02-18 14:22
I think, I'm not experienced enough to handle it.

but anyways, thanks!

**Comment by akumarujon** [comment] 2023-09-19 03:13
We(I) should fix it.

**Comment by akumarujon** [comment] 2023-09-19 13:30
> Using this line of code, it's possible to escalate many shitty thingies and even the worst, run the shebang code and execute it on system shell which leads to what we call "fiasko" for your server.

Thank you for your issue. I removed the `eval()`. I used piston API instead.

[Here is the commit link.](https://github.com/akumarujon/runner/commit/73408cb0957896572143833743090feca7abf35e)

**Comment by orzklv** [comment] 2023-09-20 09:17
please, include .env file in .gitignore asap

**Comment by akumarujon** [comment] 2023-09-20 10:52
don't worry, i revoked the token.

so i can close this issue, thank you.

**Closed by akumarujon** 2023-09-20 10:52 UTC
